device:
  adb_server: 127.0.0.1:5037

  # 对于MUMU模拟器等无法用 adb devices 命令 读取到端口的模拟器，可以开启如下选项，跳过ADB_HOST的自动检测环节
  # 但是必须保证 adb_connect 已经正确填写；如果不需要使用多开器，也可以开启如下选项，能够让你启动更快
  enable_adb_host_auto_detect: true
  #adb_connect: 127.0.0.1:7555

  package_name: com.hypergryph.arknights
  # package_name: com.hypergryph.arknights.bilibili
  activity_name: com.u8.sdk.U8UnityContext

ocr:
  # 选择 OCR 引擎，非必要
  # 设置为 auto 则使用默认优先循序: tesseract, windows_media_ocr, baidu
  engine: auto

  # 百度 API 设置，使用 baidu OCR 时需要正确填写
  baidu_api:
    app_id: STUB
    app_key: STUB
    app_secret: STUB
